### ISSUE TITLE
Cannot change the colour of the progress indicator.

### ISSUE THREAD

**Issue by ghost** [thiagocanudo/ProgressCirclesCSS#1]
The file `progress-circle.scss` contains a variable named `$color-progress-idicator` which, according the documentation, changes the colour of the progress indicator.

However, upon changing this value and re-uploading to my Webserver, the value has not changed.  Any assistance with this issue would be greatly appreciated!

**Comment by thiagocanudo** [comment]
Hello Sear-Dev, you need to compile the .scss. I recomended use Koala app to compile LESS: http://koala-app.com.

Thanks for use my project.
Thiago Canudo.

**Comment by ghost** [comment]
Hi there,

Many thanks for the help & great work on the project!

**Comment by fourroses666** [comment]
I use css, would be nice to use
```
:root{ 
    --ring-color: #f00; 
    --text-color: #f00; 
}
```
